# Generated by Django 4.1.2 on 2023-02-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_doctor_detection_price'),
        ('price', '0002_alter_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='Doctor_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
