# Generated by Django 4.1.4 on 2023-01-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_Consulation', models.DateField(null=True)),
                ('CaseDescription', models.CharField(max_length=256)),
                ('Medicine', models.CharField(max_length=256)),
                ('Doctor_id', models.IntegerField()),
                ('Patient_id', models.IntegerField()),
            ],
        ),
    ]
