# Generated by Django 4.1.4 on 2023-01-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_Photo', models.ImageField(default='', upload_to='photos/%y/%m/%d')),
                ('User_ID', models.IntegerField()),
                ('Reservation_ID', models.IntegerField()),
                ('Consulation_ID', models.IntegerField()),
            ],
        ),
    ]
