# Generated by Django 4.1.2 on 2023-02-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patient_consulation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Reservation_ID',
        ),
    ]
