# Generated by Django 4.1.4 on 2023-01-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('f', 'f'), ('m', 'm')], max_length=1, null=True)),
                ('Birthday', models.DateField()),
                ('Phone', models.IntegerField()),
                ('City', models.CharField(max_length=200)),
                ('Street', models.CharField(max_length=200)),
                ('User_Image', models.ImageField(default='', upload_to='photos/%y/%m/%d')),
                ('Type', models.CharField(choices=[('D', 'D'), ('P', 'P')], max_length=1, null=True)),
            ],
        ),
    ]
