# Generated by Django 4.1.2 on 2023-02-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_auth_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.IntegerField(default=0),
        ),
    ]
