# Generated by Django 4.1.2 on 2023-02-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
