# Generated by Django 4.1.2 on 2023-02-01 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_auth_id'),
        ('reservation', '0002_alter_reservation_id'),
        ('consulation', '0002_alter_consulation_id'),
        ('doctor', '0002_alter_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Consulation_ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='consulation.consulation'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Reservation_ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='User_ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
