# Generated by Django 4.1.2 on 2023-02-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_doctor_consulation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Detection_Price',
        ),
    ]
