# Generated by Django 4.1.2 on 2023-02-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_doctor_detection_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Detection_Price',
            field=models.CharField(default='', max_length=200),
        ),
    ]
