# Generated by Django 4.1.2 on 2023-02-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctor_detection_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Detection_Price',
            field=models.IntegerField(default=0),
        ),
    ]
