# Generated by Django 4.1.2 on 2023-02-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_doctor_detection_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Detection_Price',
            new_name='Price',
        ),
    ]
