# Generated by Django 4.1.4 on 2023-01-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reservation_Number', models.IntegerField()),
                ('Booking_Date', models.DateField(null=True)),
                ('Patient_ID', models.IntegerField()),
                ('Doctor_ID', models.IntegerField()),
            ],
        ),
    ]
