# Generated by Django 4.1.2 on 2023-02-01 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_patient_reservation_id'),
        ('doctor', '0004_remove_doctor_consulation_id_and_more'),
        ('reservation', '0003_remove_reservation_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Doctor_ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='Patient_ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
